"""EhViewer-compatible tables stored inside the RSViewer database."""

EHVIEWER_USER_VERSION = 7

EHVIEWER_TABLES = (
    "DOWNLOADS",
    "DOWNLOAD_DIRNAME",
    "DOWNLOAD_LABELS",
    "Gallery_Tags",
    "BOOKMARKS",
    "HISTORY",
    "LOCAL_FAVORITES",
    "QUICK_SEARCH",
    "FILTER",
    "Black_List",
    "android_metadata",
)

REQUIRED_LIBRARY_TABLES = {
    "DOWNLOADS",
    "DOWNLOAD_DIRNAME",
    "DOWNLOAD_LABELS",
    "Gallery_Tags",
}

EHVIEWER_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS DOWNLOADS (
    GID INTEGER PRIMARY KEY NOT NULL,
    TOKEN TEXT,
    TITLE TEXT,
    TITLE_JPN TEXT,
    THUMB TEXT,
    CATEGORY INTEGER NOT NULL,
    POSTED TEXT,
    UPLOADER TEXT,
    RATING REAL NOT NULL,
    SIMPLE_LANGUAGE TEXT,
    STATE INTEGER NOT NULL,
    LEGACY INTEGER NOT NULL,
    TIME INTEGER NOT NULL,
    LABEL TEXT,
    ARCHIVE_URI TEXT
);

CREATE TABLE IF NOT EXISTS DOWNLOAD_DIRNAME (
    GID INTEGER PRIMARY KEY NOT NULL,
    DIRNAME TEXT
);

CREATE TABLE IF NOT EXISTS DOWNLOAD_LABELS (
    _id INTEGER PRIMARY KEY,
    LABEL TEXT,
    TIME INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Gallery_Tags (
    GID INTEGER PRIMARY KEY NOT NULL,
    ROWS TEXT,
    ARTIST TEXT,
    COSPLAYER TEXT,
    CHARACTER TEXT,
    FEMALE TEXT,
    "GROUP" TEXT,
    LANGUAGE TEXT,
    MALE TEXT,
    MISC TEXT,
    MIXED TEXT,
    OTHER TEXT,
    PARODY TEXT,
    RECLASS TEXT,
    CREATE_TIME INTEGER,
    UPDATE_TIME INTEGER
);

CREATE TABLE IF NOT EXISTS BOOKMARKS (
    GID INTEGER PRIMARY KEY NOT NULL,
    TOKEN TEXT,
    TITLE TEXT,
    TITLE_JPN TEXT,
    THUMB TEXT,
    CATEGORY INTEGER NOT NULL,
    POSTED TEXT,
    UPLOADER TEXT,
    RATING REAL NOT NULL,
    SIMPLE_LANGUAGE TEXT,
    PAGE INTEGER NOT NULL,
    TIME INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS HISTORY (
    GID INTEGER PRIMARY KEY NOT NULL,
    TOKEN TEXT,
    TITLE TEXT,
    TITLE_JPN TEXT,
    THUMB TEXT,
    CATEGORY INTEGER NOT NULL,
    POSTED TEXT,
    UPLOADER TEXT,
    RATING REAL NOT NULL,
    SIMPLE_LANGUAGE TEXT,
    MODE INTEGER NOT NULL,
    TIME INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS LOCAL_FAVORITES (
    GID INTEGER PRIMARY KEY NOT NULL,
    TOKEN TEXT,
    TITLE TEXT,
    TITLE_JPN TEXT,
    THUMB TEXT,
    CATEGORY INTEGER NOT NULL,
    POSTED TEXT,
    UPLOADER TEXT,
    RATING REAL NOT NULL,
    SIMPLE_LANGUAGE TEXT,
    TIME INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS QUICK_SEARCH (
    _id INTEGER PRIMARY KEY,
    NAME TEXT,
    MODE INTEGER NOT NULL,
    CATEGORY INTEGER NOT NULL,
    KEYWORD TEXT,
    ADVANCE_SEARCH INTEGER NOT NULL,
    MIN_RATING INTEGER NOT NULL,
    PAGE_FROM INTEGER NOT NULL,
    PAGE_TO INTEGER NOT NULL,
    TIME INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS FILTER (
    _id INTEGER PRIMARY KEY,
    MODE INTEGER NOT NULL,
    TEXT TEXT,
    ENABLE INTEGER
);

CREATE TABLE IF NOT EXISTS Black_List (
    _id INTEGER PRIMARY KEY AUTOINCREMENT,
    BADGAYNAME TEXT,
    REASON TEXT,
    ANGRYWITH TEXT,
    ADD_TIME TEXT,
    MODE INTEGER
);

CREATE INDEX IF NOT EXISTS IDX_Black_List_BADGAYNAME
    ON Black_List ("BADGAYNAME");

CREATE TABLE IF NOT EXISTS android_metadata (locale TEXT);
"""


def ensure_ehviewer_schema(connection):
    connection.executescript(EHVIEWER_SCHEMA_SQL)


def table_names(connection):
    return {
        str(row[0])
        for row in connection.execute(
            "SELECT name FROM sqlite_master WHERE type = 'table'"
        )
    }


def table_columns(connection, table):
    return tuple(
        str(row[1])
        for row in connection.execute(f'PRAGMA table_info("{table}")')
    )
